### ISSUE TITLE
Time Service not running on Windows Server VMs

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/vm-scale-set-issues#1]
Originally opened as [Service Fabric issue](https://github.com/Azure/service-fabric-issues/issues/162)

VM clock drifts up to couple seconds a day due to virtualized nature of the environment, it makes it inconvenient to even use local machine time for logging.

Would be great if you configured VMs to run Time Service by default as it seems like something everybody could benefit from.

I know we can prepare sysprep-ed images with TS on or run VM extension but this one could really be a default for everybody

Thoughts?

**Comment by gbowerman** [comment]
Hi @TarasRoshko - thanks for logging our first VM scale set issue. 
VM scale sets operate at the control plane and don't have access to settings inside VMs, so this is not related to scale sets. 
It looks like you're asking for more Azure platform images to enable the time service. I'll forward your suggestion to the OS team and close this VMSS issue.

**Comment by gbowerman** [comment]
In the meantime you could write a VM custom script extension to start the Time Service as a workaround for VM images which do not set it.
