### ISSUE TITLE
When I delete a VM scale set in the Azure Portal the corresponding auto scale settings are not deleted

### ISSUE THREAD

**Issue by andwie** [Azure/vm-scale-set-issues#4]
Recently I needed to change the VM names of the VMs in a provisioned scale set.  I updated the ARM template to indicate the new name for the scale set.  Then I deleted the scale set from my existing resource group via the Azure Portal.  Then when I deployed my updated ARM template I got this error message:

TargetResourceIdIsImmutable
The autoscale setting 'autoscale-<scale set name>’ under resource group 
‘<resource group name>’ is referencing target resource '/subscriptions/<subscription id>/resourceGroups/<resource group name>/providers/Microsoft.Compute/virtualMachineScaleSets/<VM Scale Set Name>’. The target resource reference is immutable. If you want to change it, please create a new autoscale setting with a different name.

If I delete a scale set from the Azure Portal shouldn't it also delete the corresponding auto scale setting?

**Comment by gbowerman** [comment]
@andwie thanks for loggin this. Looks like a good suggestion, I'll raise it with the portal team.

**Comment by gbowerman** [comment]
@andwie the message back from the portal team is that in general deleting a single resource from the portal does not delete linked or associated resources. This purpose is served by resource groups. I.e. create all resources with a similar lifecycle in the same resource group, and then delete the resource group when done.

**Comment by andrew-wiegand-q2** [comment]
@gbowerman thank you for the reply.  For our application we have been creating a single resource group for our azure resources per environment.  So we have a production resource group and a test resource group, etc.  It wouldn't be too feasible to delete the entire resource group.  I was able to delete the autoscale settings via the resources.azure.com site so for us the issue is solved.

**Comment by andwie** [comment]
@gbowerman thank you for the reply.  For us we have been creating a resource group for our application per each environment.  So we will have a test resource group and a production resource group, etc.  It wouldn't be easy for us to delete the entire resource group.  I was able to delete the autoscale settings via the resources.azure.com site so the issue is solved for us.

**Comment by gbowerman** [comment]
Thanks for following up.
