### ISSUE TITLE
Support rolling update configuration in Azure templates

### ISSUE THREAD

**Issue by gbowerman** [Azure/vm-scale-set-issues#5]
See: [Rolling update vm scale set](https://www.reddit.com/r/AZURE/comments/67unod/rolling_update_vm_scale_set/)

**Comment by clusteratlas** [comment]
+1, following.

**Comment by gbowerman** [comment]
Please note VMSS Rolling upgrade is now in preview. You can sign up here: https://github.com/gbowerman/azure-myriad/tree/master/preview/upgrade
